import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

interface HomeProps {
  projects: {
    id: string;
    attributes: {
      title: string;
    };
  }[];
}

const Home: NextPage<HomeProps> = ({ projects }) => {
  console.log(projects);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {projects.map((project, key) => {
        return <div key={key}>{project.attributes.title}</div>;
      })}
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: process.env.REACT_APP_BACKEND_URL,
    cache: new InMemoryCache(),
    connectToDevTools: true,
  });

  const { data } = await client.query({
    query: gql`
      query getProjects {
        projects {
          data {
            id
            attributes {
              title
            }
          }
        }
      }
    `,
  });

  return {
    props: {
      projects: await data.projects.data,
    },
  };
}
